### ISSUE TITLE
Cannot call method 'serialize' of undefined on signIn method

### ISSUE THREAD

**Issue by torstenfeld** [heartsentwined/ember-auth#127]
Hi,

I tried to implement ember-auth today, but I'm always receiving "Cannot call method 'serialize' of undefined" with the signIn method.

Below you can find the call stack, ember versions, the auth object and the controller from which I call the signin. 

As far as I could see in the debugger, the issue seems to happen in the following line after the second get$ iteration: 

```
return get$(this$, '_request').signIn(url, get$(this$, '_strategy').serialize(opts)).then((this$1 = this$, function(response) {
```

```
Cannot call method 'serialize' of undefined app.js:560
TypeError: Cannot call method 'serialize' of undefined
    at Ember.Object.extend.signIn (http://localhost/mycourt-web/js/libs/ember-auth.js:83:77)
    at new Promise (http://localhost/mycourt-web/js/libs/ember-1.2.0.js:8277:9)
    at Ember.Object.extend.signIn (http://localhost/mycourt-web/js/libs/ember-auth.js:81:14)
    at App.LoginController.Ember.Controller.extend.actions.login (http://localhost/mycourt-web/js/app.js:544:18)
    at Ember.ActionHandler.Ember.Mixin.create.send (http://localhost/mycourt-web/js/libs/ember-1.2.0.js:16089:37)
    at http://localhost/mycourt-web/js/libs/ember-1.2.0.js:34445:25
    at Object.Backburner.run (http://localhost/mycourt-web/js/libs/ember-1.2.0.js:5716:26)
    at Object.Ember.run (http://localhost/mycourt-web/js/libs/ember-1.2.0.js:6082:26)
    at Object.Ember.onLoad.ActionHelper.registerAction.ActionHelper.registeredActions.(anonymous function).handler (http://localhost/mycourt-web/js/libs/ember-1.2.0.js:34443:15)
    at HTMLButtonElement.<anonymous> (http://localhost/mycourt-web/js/libs/ember-1.2.0.js:19567:25) 
```

```
DEBUG: ------------------------------- 
DEBUG: Ember      : 1.2.0 
DEBUG: Ember Data : 1.0.0-beta.2 
DEBUG: Handlebars : 1.0.0 
DEBUG: jQuery     : 1.9.1 
DEBUG: ------------------------------- 
```

```
App.Auth = Em.Auth.extend({
    request: 'jquery',
    response: 'json',

    strategy: 'token',
    tokenKey: 'auth_token',
    tokenLocation: 'param',
    tokenIdKey: 'user_id',

    session: 'cookie',

    signInEndPoint: '/signin',
    signOutEndPoint: '/signout',

    baseUrl: 'http://localhost:5555/api/v1'
});
```

```
App.LoginController = Ember.Controller.extend({
    email: null,
    password: null,

    actions: {
        tabSignup: function() {
            mixpanel.track('login-tab-signup');
            console.log('tabSignup');
        },
        tabLogin: function() {
            mixpanel.track('login-tab-login');
            console.log('tabLogin');
        },
        login: function() {
            var self = this;
            mixpanel.track('login-button-login');
            var email = Ember.$('#signupEmail').val();
            self.set('email', email);
            var password = Ember.$('#signupPassword').val();
            self.set('password', password);
            var auth = self.get('auth');
            auth.signIn({
                data: {
                    email: email,
                    password: password
                }
            })
                .then(function() {
                    var userId = auth.get('userId');
                    var token = auth.get('authToken');
                    console.log('auth success', 'userId', userId);
                })
                .fail(function(e) {
                    console.log('auth fail');
                    console.log(e.message);
                    console.log(e.stack);
                });
            self.set('email', null);
            self.set('password', null);
            self.transitionToRoute('index');
        }
    }
});
```

**Comment by torstenfeld** [comment]
Nevermind, I added the includes for 
- ember-auth-strategy-token.min.js
- ember-auth-response-json.min.js
- ember-auth-session-cookie.min.js

and it seems to be working now. ;)
