### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by pedrokost** [heartsentwined/ember-auth#133]
Hi,

I am having some issues with testing my signin/signout and related features of my app. The app works, but the test fail.

For testing, I use a `QUnit` with `testem` (I also tried teaspoon)

``` coffeescript
test "after signin, should redirect user back to previous page", ->
    visit '/library'
    fillIn '.signin-email', 'example@example.com'
    fillIn '.signin-password', 'examplepass'
    click '.signin-btn'
    andThen ->
        equal(testing().path(), 'library', "Should redirect back to library (was #{testing().path()})")
```

After running the test, I get a failure:
([screenshot here](http://i.imgur.com/cyJ1hL1) )

```
Authentication: visiting restricted page as non authenticated user: after signin, should redirect user back to previous page (2, 0, 2)Rerun544 ms
{user_id: 2, auth_token: wVveiyDLuXBXu69pQ2XQwg}
Source: 
    at Test.QUnitAdapter.Test.Adapter.extend.exception (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:50149:5)
    at superWrapper [as exception] (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:13374:16)
    at Object.onerror (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:50009:22)
    at onerror (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:20453:16)
    at EventTarget.trigger (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:20286:22)
    at null.<anonymous> (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:20439:14)
    at EventTarget.trigger (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:20286:22)
    at http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:20588:17
Should redirect back to library (was signin)
Expected:   
"library"
Result: 
"signin"
Diff:   
"library" "signin" 
Source: 
    at http://localhost:7357/public/assets/spec/javascripts/integration/authentication_pages_spec.js.js:22:14
    at andThen (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:50258:20)
    at http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:49817:21
    at isolate (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:49989:14)
    at http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:49972:12
    at invokeCallback (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:20463:19)
    at null.<anonymous> (http://localhost:7357/public/assets/application-aad0a1b2c887cc25124c361787446e83.js:20513:11)
```

Also, auth.coffee:

``` coffeescript
App.Auth = Em.Auth.extend
  request: 'jquery'
  response: 'json'
  strategy: 'token'
  session: 'cookie'
  modules: [
    'emberData',
    'authRedirectable',
    'actionRedirectable'
  ]

  signInEndPoint: '/signin'
  signOutEndPoint: '/signout'
  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'
  tokenLocation: 'param'
  emberData:
    userModel: 'user'  # create user model on login
  authRedirectable:
    route: 'signin'
  actionRedirectable:
    signInRoute: 'library'
    # signInSmart: true
    # signInBlacklist: ['signin']
    signOutRoute: 'index'
```

I am unable to find the source of the error, so maybe it is something to do with ember-auth. Any ideas would be very appreciated.

**Comment by pedrokost** [comment]
This issue can be closed as invalid. It was a bug in [my coffeescript which caused the problem](http://stackoverflow.com/questions/20912193/ember-auth-signin-test-fails-with-json).
